name: mpitapk
description: A new Flutter project.


version: 1.0.0+1


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  jumping_bottom_nav_bar: ^0.1.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/images/

  uses-material-design: true